/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabancario;

import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;
import sistemabancario.dados.Conta;
import sistemabancario.dados.ContaCorrente;
import sistemabancario.dados.ContaEspecial;
import sistemabancario.dados.ContaPoupanca;
import sistemabancario.dados.Pessoa;
import sistemabancario.dados.StatusConta;
import sistemabancario.nucleo.Contexto;
import sistemabancario.nucleo.ValidadorCampo;
import sistemabancario.nucleo.ValidadorTipo;

/**
 *
 * @author Peterson Mashni
 */
public class FrmEditaConta extends FrmPadrao {

    private final Pessoa titular;
    private final FrmCadastroConta frmCadastro;
    private Conta conta;

    /**
     * Creates new form FrmNovaConta
     */
    public FrmEditaConta(FrmPrincipal frmPrincipal, FrmCadastroConta frmCadastro, Pessoa pessoa, Conta conta) {
        super(frmPrincipal);
        initComponents();

        validador.add(new ValidadorCampo(txtAgencia, "Agência", ValidadorTipo.NumeroPositivo));
        validador.add(new ValidadorCampo(txtConta, "Nº Conta", ValidadorTipo.NumeroPositivo));
        validador.add(new ValidadorCampo(txtSenha, "Senha", ValidadorTipo.NaoVazio));

        this.frmCadastro = frmCadastro;
        this.titular = pessoa;
        this.conta = conta;

        txtTitular.setText(titular.getNome());
        if (conta != null) {
            this.setTitle("Alteração de Conta");

            txtAgencia.setText(conta.getAgencia());
            txtConta.setText(conta.getNumeroConta());

            txtAgencia.setEnabled(false);
            txtConta.setEnabled(false);

            if (conta.getStatus() == StatusConta.Encerrada)
            {
                txtSenha.setEnabled(false);
                txtConfirmacaoSenha.setEnabled(false);
                btnSalvar.setEnabled(false);
            }
            
            txtSenha.setText(conta.getSenha());
            txtConfirmacaoSenha.setText(conta.getSenha());

            cbTipoConta.setSelectedItem(conta.getTipoConta().toString());
            cbTipoConta.setEnabled(false);

            txtStatusConta.setText(conta.getStatus().toString());

            habilitaCamposConta();

            if (cbTipoConta.getSelectedItem().toString().equals("Poupanca")) {
                txtTaxaRendimento.setText(decimalFormat.format(((ContaPoupanca) conta).getTaxaRendimento()));
            } else if (cbTipoConta.getSelectedItem().toString().equals("Corrente")) {
                txtTaxaMensal.setText(decimalFormat.format(((ContaCorrente) conta).getTaxaMensal()));
            } else {
                txtTaxaMensal.setText(decimalFormat.format(((ContaEspecial) conta).getTaxaMensal()));
                txtTaxaJuros.setText(decimalFormat.format(((ContaEspecial) conta).getTaxaJuros()));
                txtLimiteConta.setText(decimalFormat.format(((ContaEspecial) conta).getLimiteConta()));
            }
        }
    }

    private void habilitaCamposConta() {
        txtTaxaRendimento.setEnabled(false);
        txtTaxaMensal.setEnabled(false);
        txtTaxaJuros.setEnabled(false);
        txtLimiteConta.setEnabled(false);

        if (conta.getStatus() == StatusConta.Ativa) {
            if (cbTipoConta.getSelectedItem().toString().equals("Poupanca")) {
                txtTaxaRendimento.setEnabled(true);
            } else if (cbTipoConta.getSelectedItem().toString().equals("Corrente")) {
                txtTaxaMensal.setEnabled(true);
            } else if (cbTipoConta.getSelectedItem().toString().equals("Especial")) {
                txtTaxaMensal.setEnabled(true);
                txtTaxaJuros.setEnabled(true);
                txtLimiteConta.setEnabled(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtAgencia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtConta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTitular = new javax.swing.JTextField();
        cbTipoConta = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtTaxaMensal = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTaxaJuros = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        txtLimiteConta = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTaxaRendimento = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txtConfirmacaoSenha = new javax.swing.JPasswordField();
        txtStatusConta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setTitle("Nova Conta");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nº Agência:");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Nº Conta:");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Tipo:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Titular:");

        txtTitular.setEditable(false);
        txtTitular.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtTitular.setEnabled(false);

        cbTipoConta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Corrente", "Especial", "Poupanca" }));
        cbTipoConta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTipoContaItemStateChanged(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Taxa Mensal:");

        txtTaxaMensal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtTaxaMensal.setToolTipText("");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Taxa Juros:");

        txtTaxaJuros.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtTaxaJuros.setToolTipText("");
        txtTaxaJuros.setEnabled(false);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Limite:");

        txtLimiteConta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtLimiteConta.setToolTipText("");
        txtLimiteConta.setEnabled(false);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Rendimento:");

        txtTaxaRendimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtTaxaRendimento.setToolTipText("");
        txtTaxaRendimento.setEnabled(false);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Senha:");

        jLabel5.setText("Confirmação Senha:");

        txtStatusConta.setEditable(false);
        txtStatusConta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtStatusConta.setEnabled(false);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Status:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(170, 170, 170))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cbTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtTaxaRendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(60, 60, 60)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtConta, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtStatusConta, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap(32, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTaxaJuros, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTaxaMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel5))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLimiteConta, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(txtConfirmacaoSenha))
                        .addContainerGap(33, Short.MAX_VALUE))))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel10, jLabel11, jLabel14, jLabel2, jLabel3, jLabel4});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel12, jLabel13, jLabel6});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtTaxaRendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtTaxaMensal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStatusConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTaxaJuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLimiteConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtConfirmacaoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29))
        );

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (!validador.validar()) {
            String campos = "";
            for (ValidadorCampo c : validador.getCampos()) {
                if (!c.isCampoValido()) {
                    campos += ", " + c.getNomeCampo();
                }
            }
            campos += ".";
            campos = campos.substring(2);

            JOptionPane.showMessageDialog(null, "Por favor, verifique os campos: " + campos, "Aviso", JOptionPane.OK_OPTION);
            return;
        }

        if (!txtSenha.getText().equals(txtConfirmacaoSenha.getText())) {
            JOptionPane.showMessageDialog(null, "Por favor, verifique a senha, pois não confere com a Confirmação!", "Aviso", JOptionPane.OK_OPTION);
            return;
        }

        boolean novo = conta == null;

        if (cbTipoConta.getSelectedItem().toString().equals("Poupanca")) {

            Float taxaRendimento = 0F;
            try {
                taxaRendimento = decimalFormat.parse(txtTaxaRendimento.getText().trim()).floatValue();
            } catch (Exception e) {
            }
            if (taxaRendimento == 0F) {
                JOptionPane.showMessageDialog(null, "Por favor, verifique o valor da Taxa de Rendimento da Conta!", "Aviso", JOptionPane.OK_OPTION);
                return;
            }

            if (conta == null) {
                conta = new ContaPoupanca(titular, taxaRendimento);
            } else {
                ((ContaPoupanca) conta).setTaxaRendimento(taxaRendimento);
            }

        } else if (cbTipoConta.getSelectedItem().toString().equals("Corrente")) {

            Float taxaMensal = 0F;
            try {

                taxaMensal = decimalFormat.parse(txtTaxaMensal.getText().trim()).floatValue();
            } catch (Exception e) {
            }
            if (taxaMensal == 0F) {
                JOptionPane.showMessageDialog(null, "Por favor, verifique o valor da Taxa de Mensal da Conta!", "Aviso", JOptionPane.OK_OPTION);
                return;
            }
            if (conta == null) {
                conta = new ContaCorrente(titular, taxaMensal);
            } else {
                ((ContaCorrente) conta).setTaxaMensal(taxaMensal);
            }

        } else {

            Float taxaMensal = 0F;
            try {
                taxaMensal = decimalFormat.parse(txtTaxaMensal.getText().trim()).floatValue();
            } catch (Exception e) {
            }
            if (taxaMensal == 0F) {
                JOptionPane.showMessageDialog(null, "Por favor, verifique o valor da Taxa de Mensal da Conta!", "Aviso", JOptionPane.OK_OPTION);
                return;
            }

            Float taxaJuros = 0F;
            try {
                taxaJuros = decimalFormat.parse(txtTaxaJuros.getText().trim()).floatValue();
            } catch (Exception e) {
            }
            if (taxaJuros == 0F) {
                JOptionPane.showMessageDialog(null, "Por favor, verifique o valor da Taxa de Juros da Conta!", "Aviso", JOptionPane.OK_OPTION);
                return;
            }

            Float limiteConta = 0F;
            try {
                limiteConta = decimalFormat.parse(txtLimiteConta.getText().trim()).floatValue();
            } catch (Exception e) {
            }
            if (limiteConta == 0F) {
                JOptionPane.showMessageDialog(null, "Por favor, verifique o valor do Limite da Conta!", "Aviso", JOptionPane.OK_OPTION);
                return;
            }

            if (conta == null) {
                conta = new ContaEspecial(titular, taxaMensal, taxaJuros, limiteConta);
            } else {
                ((ContaEspecial) conta).setTaxaMensal(taxaMensal);
            }
            ((ContaEspecial) conta).setTaxaJuros(taxaJuros);
            ((ContaEspecial) conta).setLimiteConta(limiteConta);

        }

        if (!(novo || conta.getSenha().equals(txtSenha.getText()))) {
            Contexto.log("cadastroContas", "Senha de Conta Alterada " + txtAgencia.getText() + "/" + txtConta.getText());
        }

        conta.setAgencia(txtAgencia.getText());
        conta.setNumeroConta(txtConta.getText());
        conta.setSenha(txtSenha.getText());

        if (novo) {
            Contexto.getColecaoContas().put(conta.toString(), conta);
            JOptionPane.showMessageDialog(null, "Conta Adicionada com Sucesso!", "Ok", JOptionPane.OK_OPTION);
            Contexto.log("cadastroContas", "Conta Adicionada " + txtAgencia.getText() + "/" + txtConta.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Conta Alterada com Sucesso!", "Ok", JOptionPane.OK_OPTION);
            Contexto.log("cadastroContas", "Conta Alterada " + txtAgencia.getText() + "/" + txtConta.getText());
        }

        frmCadastro.buscarContas();

        btnCancelarActionPerformed(null);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cbTipoContaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTipoContaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            habilitaCamposConta();
        }
    }//GEN-LAST:event_cbTipoContaItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbTipoConta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtAgencia;
    private javax.swing.JPasswordField txtConfirmacaoSenha;
    private javax.swing.JTextField txtConta;
    private javax.swing.JFormattedTextField txtLimiteConta;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtStatusConta;
    private javax.swing.JFormattedTextField txtTaxaJuros;
    private javax.swing.JFormattedTextField txtTaxaMensal;
    private javax.swing.JFormattedTextField txtTaxaRendimento;
    private javax.swing.JTextField txtTitular;
    // End of variables declaration//GEN-END:variables

}
