/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabancario;

import java.util.Collections;
import java.util.Date;
import javax.swing.JOptionPane;
import sistemabancario.dados.Conta;
import sistemabancario.dados.ContaEspecial;
import sistemabancario.dados.OperacaoConta;
import sistemabancario.dados.TipoConta;
import sistemabancario.dados.TipoOperacao;
import sistemabancario.nucleo.Contexto;
import sistemabancario.nucleo.ValidadorCampo;
import sistemabancario.nucleo.ValidadorTipo;

/**
 *
 * @author Peterson Mashni
 */
public class FrmExtrato extends FrmPadrao {

    /**
     * Creates new form FrmExtrato
     */
    public FrmExtrato(FrmPrincipal frmPrincipal) {
        super(frmPrincipal);
        initComponents();
        validador.add(new ValidadorCampo(txtAgencia, "Agência", ValidadorTipo.NaoVazio));
        validador.add(new ValidadorCampo(txtConta, "Conta", ValidadorTipo.NaoVazio));
        validador.add(new ValidadorCampo(txtSenha, "Senha", ValidadorTipo.NaoVazio));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtAgencia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtConta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnImprimir = new javax.swing.JButton();

        setTitle("Consulta Extrato");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nº Agência:");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Nº Conta:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Senha:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConta, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel12, jLabel2, jLabel3});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(btnImprimir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnImprimir)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        if (!validador.validar()) {
            String campos = "";
            for (ValidadorCampo c : validador.getCampos()) {
                if (!c.isCampoValido()) {
                    campos += ", " + c.getNomeCampo();
                }
            }
            campos += ".";
            campos = campos.substring(2);

            JOptionPane.showMessageDialog(null, "Por favor, verifique os campos: " + campos, "Aviso", JOptionPane.OK_OPTION);
            return;
        }

        Conta c = Contexto.getColecaoContas().get("Conta{" + "agencia=" + txtAgencia.getText() + ", numeroConta=" + txtConta.getText() + '}');

        if (c == null) {
            JOptionPane.showMessageDialog(null, "Conta não encontrada!", "Aviso", JOptionPane.OK_OPTION);
        } else if (c.getSenha() == null || !c.getSenha().equals(txtSenha.getText())) {
            Contexto.log("extrato", "Tentativa de emissão de extrato bloqueada por senha incorreta na Conta " + txtAgencia.getText()+"/"+txtConta.getText());
            JOptionPane.showMessageDialog(null, "Senha Incorreta!", "Aviso", JOptionPane.OK_OPTION);
        } else {
            Contexto.printLine("-------------------------------------------------");
            Contexto.printLine("        BANCO X - EXTRATO DE MOVIMENTACAO        ");
            Contexto.printLine("-------------------------------------------------");

            Contexto.printLine("TITULAR..: " + c.getTitular().getNome());
            Contexto.printLine("AGENCIA..: " + c.getAgencia());
            Contexto.printLine("CONTA....: " + c.getNumeroConta());
            Contexto.printLine("");
            if (c.getOperacoes().isEmpty()) {
                Contexto.printLine("*** CONTA SEM MOVIMENTAÇÃO ***");
                Contexto.printLine("");
            } else {
                Contexto.printLine("DATA  OPERACAO               VALOR          SALDO");
                Contexto.printLine("----- -------------  -------------  -------------");
                Contexto.printLine(mesAnoFormat.format(c.getDataAbertura()) + " SALDO INICIAL                          0,00");

                for (OperacaoConta op : c.getOperacoes()) {
                    String valor = decimalFormat.format(op.getValor());
                    String saldo = decimalFormat.format(op.getSaldo());
                    valor = String.join("", Collections.nCopies(13 - valor.length(), " ")) + valor;
                    saldo = String.join("", Collections.nCopies(13 - saldo.length(), " ")) + saldo;
                    Contexto.printLine(
                            mesAnoFormat.format(op.getDataOperacao()) + "  "
                            + (op.getTipoOperacao() == TipoOperacao.Credito ? "DEPOSITO      " : "SAQUE         ")
                            + valor + "  " + saldo);
                }
            }

            if (c.getTipoConta() == TipoConta.Especial) {
                Contexto.printLine("");
                Contexto.printLine("LIMITE DA CONTA..........: " + decimalFormat.format(c.getSaldo()));
                
            }

            Contexto.printLine("");
            Contexto.printLine("SALDO NA DATA............: " + decimalFormat.format(c.getSaldo()));

            if (c.getTipoConta() == TipoConta.Especial) {
                Contexto.printLine("");
                Contexto.printLine("SALDO DISP. COM O LIMITE.: " + decimalFormat.format(c.getSaldo() + ((ContaEspecial)c).getLimiteConta()));
            }
            Contexto.printLine("");

            Contexto.printLine("-------------------------------------------------");
            Contexto.printLine("DATA/HORA: " + datetimeFormat.format(new Date()));
            Contexto.printLine("");
            Contexto.printLine("");
            Contexto.printLine("");
            Contexto.log("extrato", "Emissão de extrato autorizada na Conta " + txtAgencia.getText()+"/"+txtConta.getText());
            frmPrincipal.showForm(FrmImpressora.class);
            JOptionPane.showMessageDialog(null, "Extrato emitido com Sucesso!", "Aviso", JOptionPane.OK_OPTION);
            fecharForm();
        }
    }//GEN-LAST:event_btnImprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtAgencia;
    private javax.swing.JTextField txtConta;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
