/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabancario;

import java.awt.event.ActionEvent;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JMenuItem;
import sistemabancario.dados.*;
import sistemabancario.nucleo.Contexto;

/**
 *
 * @author Peterson Mashni
 */
public class FrmPrincipal extends javax.swing.JFrame {

    public class ItemMenu {

        public ItemMenu(JMenuItem menuItem, Class<?> formClass, boolean acessoCaixa) {
            this.menuItem = menuItem;
            this.formClass = formClass;
            this.acessoCaixa = acessoCaixa;
        }

        public JMenuItem menuItem;
        public Class<?> formClass;
        public boolean acessoCaixa;
    }

    private ImpressoraTela impressoraTela = new ImpressoraTela();
    private LogTela logTela = new LogTela();
    private ArrayList<ItemMenu> listaMenu = new ArrayList<ItemMenu>();

    public ImpressoraTela getImpressoraTela() {
        return impressoraTela;
    }

    public LogTela getLogTela() {
        return logTela;
    }

    /**
     * Creates new form FramePrincipal
     */
    public FrmPrincipal() {
        initComponents();
        setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        setContentPane(jdPanel);

        listaMenu.add(new ItemMenu(menuCadastrosFuncionarios, FrmCadastroFuncionario.class, false));
        listaMenu.add(new ItemMenu(menuCadastrosPessoasFisicas, FrmCadastroPessoaFisica.class, false));
        listaMenu.add(new ItemMenu(menuCadastrosPessoasJuridicas, FrmCadastroPessoaJuridica.class, false));
        listaMenu.add(new ItemMenu(menuCadastrosContas, FrmCadastroConta.class, false));
        listaMenu.add(new ItemMenu(menuOperacoesSaque, FrmSaque.class, true));
        listaMenu.add(new ItemMenu(menuOperacoesDeposito, FrmDeposito.class, true));
        listaMenu.add(new ItemMenu(menuOperacoesExtrato, FrmExtrato.class, true));
        listaMenu.add(new ItemMenu(menuOperacoesSaldo, FrmSaldo.class, true));
        listaMenu.add(new ItemMenu(menuRelatoriosCadastroClientes, FrmRelCadastros.class, false));
        listaMenu.add(new ItemMenu(menuExibirImpressora, FrmImpressora.class, true));
        listaMenu.add(new ItemMenu(menuExibirLog, FrmLog.class, true));
        listaMenu.add(new ItemMenu(menuRelatoriosContas, FrmRelContas.class, false));
        listaMenu.add(new ItemMenu(menuEncerrarConta, FrmEncerramentoConta.class, false));

        for (int j = 0; j < listaMenu.size(); j++) {
            listaMenu.get(j).menuItem.setAction(new AbstractAction(listaMenu.get(j).menuItem.getText()) {
                @Override
                public void actionPerformed(ActionEvent ae) {
                    for (int i = 0; i < listaMenu.size(); i++) {
                        if (ae.getActionCommand().equals(listaMenu.get(i).menuItem.getActionCommand())) {
                            showForm(listaMenu.get(i).formClass);
                        }
                    }
                }
            });
        }

        Contexto.registraImpressora(impressoraTela);
        Contexto.registraLogDevice(logTela);

        Funcionario f = new Funcionario(1, "MASTER", CargoFuncionario.Master, "1234");
        Contexto.getColecaoFuncionarios().put(f.getCodigo(), f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdPanel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        menuCadastrosFuncionarios = new javax.swing.JMenuItem();
        menuCadastrosPessoasFisicas = new javax.swing.JMenuItem();
        menuCadastrosPessoasJuridicas = new javax.swing.JMenuItem();
        menuCadastrosContas = new javax.swing.JMenuItem();
        menuOperacoes = new javax.swing.JMenu();
        menuOperacoesSaque = new javax.swing.JMenuItem();
        menuOperacoesDeposito = new javax.swing.JMenuItem();
        menuOperacoesExtrato = new javax.swing.JMenuItem();
        menuOperacoesSaldo = new javax.swing.JMenuItem();
        menuEncerrarConta = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        menuRelatoriosCadastroClientes = new javax.swing.JMenuItem();
        menuRelatoriosContas = new javax.swing.JMenuItem();
        menuExibir = new javax.swing.JMenu();
        menuExibirLog = new javax.swing.JMenuItem();
        menuExibirImpressora = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        menuLogon = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Bancário");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jdPanel.setForeground(new java.awt.Color(240, 240, 240));
        jdPanel.setName(""); // NOI18N

        javax.swing.GroupLayout jdPanelLayout = new javax.swing.GroupLayout(jdPanel);
        jdPanel.setLayout(jdPanelLayout);
        jdPanelLayout.setHorizontalGroup(
            jdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        jdPanelLayout.setVerticalGroup(
            jdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );

        menuCadastros.setText("Cadastros");

        menuCadastrosFuncionarios.setText("Funcionários");
        menuCadastrosFuncionarios.setActionCommand("cadastroFuncionarios");
        menuCadastros.add(menuCadastrosFuncionarios);

        menuCadastrosPessoasFisicas.setText("Pessoas Físicas");
        menuCadastros.add(menuCadastrosPessoasFisicas);

        menuCadastrosPessoasJuridicas.setText("Pessoas Jurídicas");
        menuCadastros.add(menuCadastrosPessoasJuridicas);

        menuCadastrosContas.setText("Contas");
        menuCadastrosContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrosContasActionPerformed(evt);
            }
        });
        menuCadastros.add(menuCadastrosContas);

        jMenuBar1.add(menuCadastros);

        menuOperacoes.setText("Operações");

        menuOperacoesSaque.setText("Saque");
        menuOperacoesSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOperacoesSaqueActionPerformed(evt);
            }
        });
        menuOperacoes.add(menuOperacoesSaque);

        menuOperacoesDeposito.setText("Depósito");
        menuOperacoes.add(menuOperacoesDeposito);

        menuOperacoesExtrato.setText("Extrato");
        menuOperacoes.add(menuOperacoesExtrato);

        menuOperacoesSaldo.setText("Saldo");
        menuOperacoes.add(menuOperacoesSaldo);

        menuEncerrarConta.setText("Encerrar Conta");
        menuOperacoes.add(menuEncerrarConta);

        jMenuBar1.add(menuOperacoes);

        menuRelatorios.setText("Relatórios");

        menuRelatoriosCadastroClientes.setText("Cadastro de Clientes");
        menuRelatoriosCadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatoriosCadastroClientesActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuRelatoriosCadastroClientes);

        menuRelatoriosContas.setText("Cadastro de Contas");
        menuRelatorios.add(menuRelatoriosContas);

        jMenuBar1.add(menuRelatorios);

        menuExibir.setText("Exibir");

        menuExibirLog.setText("Log");
        menuExibir.add(menuExibirLog);

        menuExibirImpressora.setText("Impressora");
        menuExibir.add(menuExibirImpressora);

        jMenuBar1.add(menuExibir);

        menuSair.setText("Sair");

        menuLogon.setText("Logout");
        menuLogon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogonActionPerformed(evt);
            }
        });
        menuSair.add(menuLogon);

        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdPanel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        logon();
    }//GEN-LAST:event_formWindowOpened

    private void logon() {
        while (!Contexto.usuarioEstaAutenticado()) {
            new FrmLogon().setVisible(true);
        }
        for (ItemMenu i : listaMenu) {
            i.menuItem.setEnabled(
                    Contexto.getFuncionarioLogado().getCargo() == CargoFuncionario.Master
                    | Contexto.getFuncionarioLogado().getCargo() == CargoFuncionario.Gerente
                    | i.acessoCaixa);
        }
    }

    private void menuLogonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogonActionPerformed
        Contexto.log("login", "Logout de usuário.");
        closeForms();
        Contexto.setFuncionarioLogado(null);
        logon();
    }//GEN-LAST:event_menuLogonActionPerformed

    private void menuCadastrosContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrosContasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastrosContasActionPerformed

    private void menuOperacoesSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOperacoesSaqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuOperacoesSaqueActionPerformed

    private void menuRelatoriosCadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatoriosCadastroClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuRelatoriosCadastroClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmPrincipal().setVisible(true);
        });
    }

    void showForm(Class<?> classForm) {
        for (JInternalFrame f : jdPanel.getAllFrames()) {
            if (f.getClass() == classForm) {
                jdPanel.moveToFront(f);
                try {
                    f.setSelected(true);
                } catch (java.beans.PropertyVetoException e) {
                }
                return;
            }
        }

        try {
            classForm.getConstructor(new Class[]{FrmPrincipal.class}).newInstance(new Object[]{this});
        } catch (Exception e) {
            Contexto.log("showForm", "Erro ao iniciar o formulário " + classForm.getName() + " \n" + e.toString());
        }
    }

    void closeForms() {
        for (JInternalFrame f : jdPanel.getAllFrames()) {
            try {
                f.setClosed(true);
            } catch (PropertyVetoException ex) {
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JDesktopPane jdPanel;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenuItem menuCadastrosContas;
    private javax.swing.JMenuItem menuCadastrosFuncionarios;
    private javax.swing.JMenuItem menuCadastrosPessoasFisicas;
    private javax.swing.JMenuItem menuCadastrosPessoasJuridicas;
    private javax.swing.JMenuItem menuEncerrarConta;
    private javax.swing.JMenu menuExibir;
    private javax.swing.JMenuItem menuExibirImpressora;
    private javax.swing.JMenuItem menuExibirLog;
    private javax.swing.JMenuItem menuLogon;
    private javax.swing.JMenu menuOperacoes;
    private javax.swing.JMenuItem menuOperacoesDeposito;
    private javax.swing.JMenuItem menuOperacoesExtrato;
    private javax.swing.JMenuItem menuOperacoesSaldo;
    private javax.swing.JMenuItem menuOperacoesSaque;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenuItem menuRelatoriosCadastroClientes;
    private javax.swing.JMenuItem menuRelatoriosContas;
    private javax.swing.JMenu menuSair;
    // End of variables declaration//GEN-END:variables

}
