/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabancario;

import java.util.Date;
import sistemabancario.dados.Conta;
import sistemabancario.dados.PessoaFisica;
import sistemabancario.dados.PessoaJuridica;
import sistemabancario.dados.StatusConta;
import sistemabancario.dados.TipoPessoa;
import sistemabancario.nucleo.Contexto;

/**
 *
 * @author Peterson Mashni
 */
public class FrmRelContas extends FrmPadrao {

    /**
     * Creates new form FrmSaldo
     */
    public FrmRelContas(FrmPrincipal frmPrincipal) {
        super(frmPrincipal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblCpfCnpj1 = new javax.swing.JLabel();
        cbTipoPessoa = new javax.swing.JComboBox<>();
        lblCpfCnpj3 = new javax.swing.JLabel();
        cbStatusConta = new javax.swing.JComboBox<>();
        btnImprimir = new javax.swing.JButton();

        setTitle("Relatório de Contas");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCpfCnpj1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCpfCnpj1.setText("Tipo de Pessoa:");

        cbTipoPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Físicas", "Jurídicas" }));

        lblCpfCnpj3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCpfCnpj3.setText("Status:");

        cbStatusConta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Ativas", "Encerradas" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblCpfCnpj1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblCpfCnpj3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbStatusConta, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCpfCnpj1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbStatusConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCpfCnpj3))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImprimir)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnImprimir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        Contexto.printLine("----------------------------------------------------------------------------------------------");
        Contexto.printLine(" BANCO X - RELATORIO DE CONTAS CADASTRADAS                        EMISSAO: " + datetimeFormat.format(new Date()));
        Contexto.printLine("----------------------------------------------------------------------------------------------");
        Contexto.printLine("");
        Contexto.printLine("CPF/CNPJ CLIENTE   AG.      CONTA        TIPO       STATUS    ULT.MOVTO                  SALDO");
        Contexto.printLine("------------------ -------- ------------ ---------- --------- ------------------- ------------");

        int i = 0;
        for (Conta c : Contexto.getColecaoContas().values()) {

            if (cbStatusConta.getSelectedIndex() == 1 & c.getStatus() == StatusConta.Encerrada) {
                continue;
            }

            if (cbStatusConta.getSelectedIndex() == 2 & c.getStatus() == StatusConta.Ativa) {
                continue;
            }

            if (cbTipoPessoa.getSelectedIndex() == 1 & c.getTitular().getTipoPessoa() == TipoPessoa.Juridica) {
                continue;
            }

            if (cbTipoPessoa.getSelectedIndex() == 2 & c.getTitular().getTipoPessoa() == TipoPessoa.Fisica) {
                continue;
            }

            Contexto.print(ajusta(c.getTitular().getTipoPessoa() == TipoPessoa.Fisica ? ((PessoaFisica) c.getTitular()).getCpf() : ((PessoaJuridica) c.getTitular()).getCnpj(), 18) + " ");
            Contexto.print(ajusta(c.getAgencia(), 8) + " ");
            Contexto.print(ajusta(c.getNumeroConta(), 12) + " ");
            Contexto.print(ajusta(c.getTipoConta().toString(), 10) + " ");
            Contexto.print(ajusta(c.getStatus().toString(), 9) + " ");

            if (c.getDataUltimoMovimento() == null) {
                Contexto.print("--/--/---- --:--:-- ");
            } else {
                Contexto.print(datetimeFormat.format(c.getDataUltimoMovimento()) + " ");
            }

            Contexto.printLine(ajustaDireita(decimalFormat.format(c.getSaldo()), 12));
            i++;
        }

        Contexto.printLine("-----------------------------------------------------------------------------------------------");
        Contexto.printLine("REGISTROS LISTADOS: " + i);
        Contexto.log("relatorioContas", "Emissão de relatório de contas");
        frmPrincipal.showForm(FrmImpressora.class);
    }//GEN-LAST:event_btnImprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JComboBox<String> cbStatusConta;
    private javax.swing.JComboBox<String> cbTipoPessoa;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCpfCnpj1;
    private javax.swing.JLabel lblCpfCnpj3;
    // End of variables declaration//GEN-END:variables
}
