/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabancario;

import java.util.Date;
import sistemabancario.dados.Pessoa;
import sistemabancario.dados.PessoaFisica;
import sistemabancario.dados.PessoaJuridica;
import sistemabancario.dados.StatusPessoa;
import sistemabancario.dados.TipoPessoa;
import sistemabancario.nucleo.Contexto;

/**
 *
 * @author Peterson Mashni
 */
public class FrmRelCadastros extends FrmPadrao {

    /**
     * Creates new form FrmSaldo
     */
    public FrmRelCadastros(FrmPrincipal frmPrincipal) {
        super(frmPrincipal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblCpfCnpj1 = new javax.swing.JLabel();
        cbTipoPessoa = new javax.swing.JComboBox<>();
        lblCpfCnpj2 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblCpfCnpj3 = new javax.swing.JLabel();
        cbStatusPessoa = new javax.swing.JComboBox<>();
        btnImprimir = new javax.swing.JButton();

        setTitle("Relatório de Cadastros");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCpfCnpj1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCpfCnpj1.setText("Tipo de Pessoa:");

        cbTipoPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Físicas", "Jurídicas" }));

        lblCpfCnpj2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCpfCnpj2.setText("Cidade:");

        lblCpfCnpj3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCpfCnpj3.setText("Status:");

        cbStatusPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Ativas", "Inativas" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblCpfCnpj2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCidade))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblCpfCnpj1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblCpfCnpj3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbStatusPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 80, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCpfCnpj1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbStatusPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCpfCnpj3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpfCnpj2)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImprimir)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnImprimir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        Contexto.printLine("----------------------------------------------------------------------------------------------");
        Contexto.printLine(" BANCO X - RELATORIO DE CADASTRO DE CLIENTES        EMISSAO: " + datetimeFormat.format(new Date()));
        Contexto.printLine("----------------------------------------------------------------------------------------------");
        Contexto.printLine("");
        Contexto.printLine("CPF/CNPJ           NOME                           CIDADE                         TELEFONE    ");
        Contexto.printLine("------------------ ------------------------------ ------------------------------ -------------");

        int i = 0;
        for (Pessoa p : Contexto.getColecaoPessoas()) {
            if (cbStatusPessoa.getSelectedIndex() == 1 & p.getStatus() == StatusPessoa.Inativa) {
                continue;
            }

            if (cbStatusPessoa.getSelectedIndex() == 2 & p.getStatus() == StatusPessoa.Ativa) {
                continue;
            }

            if (cbTipoPessoa.getSelectedIndex() == 1 & p.getTipoPessoa() == TipoPessoa.Juridica) {
                continue;
            }

            if (cbTipoPessoa.getSelectedIndex() == 2 & p.getTipoPessoa() == TipoPessoa.Fisica) {
                continue;
            }

            if (!(txtCidade.getText().isEmpty() | p.getCidade().startsWith(txtCidade.getText()))) {
                continue;
            }

            Contexto.print(ajusta(p.getTipoPessoa() == TipoPessoa.Fisica ? ((PessoaFisica) p).getCpf() : ((PessoaJuridica) p).getCnpj(), 18) + " ");
            Contexto.print(ajusta(p.getNome(), 30) + " ");
            Contexto.print(ajusta(p.getCidade(), 30) + " ");
            Contexto.printLine(p.getTelefone());

            i++;
        }

        Contexto.printLine("----------------------------------------------------------------------------------------------");
        Contexto.printLine("REGISTROS LISTADOS: " + i);
        Contexto.log("relatorioCadastros", "Emissão de relatório de cadastros");
        frmPrincipal.showForm(FrmImpressora.class);
    }//GEN-LAST:event_btnImprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JComboBox<String> cbStatusPessoa;
    private javax.swing.JComboBox<String> cbTipoPessoa;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCpfCnpj1;
    private javax.swing.JLabel lblCpfCnpj2;
    private javax.swing.JLabel lblCpfCnpj3;
    private javax.swing.JTextField txtCidade;
    // End of variables declaration//GEN-END:variables
}
