/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabancario;

import java.util.Date;
import javax.swing.JOptionPane;
import sistemabancario.dados.Conta;
import sistemabancario.dados.ContaEspecial;
import sistemabancario.dados.TipoConta;
import sistemabancario.nucleo.Contexto;
import sistemabancario.nucleo.ValidadorCampo;
import sistemabancario.nucleo.ValidadorTipo;

/**
 *
 * @author Peterson Mashni
 */
public class FrmSaldo extends FrmPadrao {

    /**
     * Creates new form FrmSaldo
     */
    public FrmSaldo(FrmPrincipal frmPrincipal) {
        super(frmPrincipal);
        initComponents();
        validador.add(new ValidadorCampo(txtAgencia, "Agência", ValidadorTipo.NaoVazio));
        validador.add(new ValidadorCampo(txtConta, "Conta", ValidadorTipo.NaoVazio));
        validador.add(new ValidadorCampo(txtSenha, "Senha", ValidadorTipo.NaoVazio));
    }

    private void buscaSaldo(boolean imprimir) {
        if (!validador.validar()) {
            String campos = "";
            for (ValidadorCampo c : validador.getCampos()) {
                if (!c.isCampoValido()) {
                    campos += ", " + c.getNomeCampo();
                }
            }
            campos += ".";
            campos = campos.substring(2);

            JOptionPane.showMessageDialog(null, "Por favor, verifique os campos: " + campos, "Aviso", JOptionPane.OK_OPTION);
            return;
        }

        Conta c = Contexto.getColecaoContas().get("Conta{" + "agencia=" + txtAgencia.getText() + ", numeroConta=" + txtConta.getText() + '}');

        if (c == null) {
            JOptionPane.showMessageDialog(null, "Conta não encontrada!", "Aviso", JOptionPane.OK_OPTION);
        } else if (c.getSenha() == null || !c.getSenha().equals(txtSenha.getText())) {
            Contexto.log("saldo", "Tentativa de emissão de saldo bloqueada por senha incorreta na Conta " + txtAgencia.getText() + "/" + txtConta.getText());
            JOptionPane.showMessageDialog(null, "Senha Incorreta!", "Aviso", JOptionPane.OK_OPTION);
        } else if (!imprimir) {
            Contexto.log("saldo", "Consulta de saldo em tela autorizada na Conta " + txtAgencia.getText() + "/" + txtConta.getText());
            JOptionPane.showMessageDialog(null, "Saldo em conta: " + decimalFormat.format(c.getSaldo()), "Saldo", JOptionPane.OK_OPTION);
            fecharForm();
        } else {
            Contexto.printLine("---------------------------------------");
            Contexto.printLine("    BANCO X - COMPROVANTE DE SALDO     ");
            Contexto.printLine("---------------------------------------");
            Contexto.printLine("TITULAR..: " + c.getTitular().getNome());
            Contexto.printLine("AGENCIA..: " + c.getAgencia());
            Contexto.printLine("CONTA....: " + c.getNumeroConta());

            if (c.getTipoConta() == TipoConta.Especial) {
                Contexto.printLine("");
                Contexto.printLine("LIMITE DA CONTA..........: " + decimalFormat.format(((ContaEspecial) c).getLimiteConta()));

            }

            Contexto.printLine("");
            Contexto.printLine("SALDO NA DATA............: " + decimalFormat.format(c.getSaldo()));

            if (c.getTipoConta() == TipoConta.Especial) {
                Contexto.printLine("");
                Contexto.printLine("SALDO DISP. COM O LIMITE.: " + decimalFormat.format(c.getSaldo() + ((ContaEspecial) c).getLimiteConta()));
            }
            Contexto.printLine("");

            Contexto.printLine("---------------------------------------");
            Contexto.printLine("DATA/HORA: " + datetimeFormat.format(new Date()));
            Contexto.printLine("");
            Contexto.printLine("");
            Contexto.printLine("");
            Contexto.log("saldo", "Impressão de saldo autorizada na Conta " + txtAgencia.getText() + "/" + txtConta.getText());
            frmPrincipal.showForm(FrmImpressora.class);
            JOptionPane.showMessageDialog(null, "Saldo emitido com Sucesso!", "Aviso", JOptionPane.OK_OPTION);
            fecharForm();

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtAgencia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtConta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnConsultar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();

        setTitle("Consulta Saldo");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nº Agência:");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Nº Conta:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Senha:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConta, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSenha)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel12, jLabel2, jLabel3});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnImprimir)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnImprimir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        buscaSaldo(false);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        buscaSaldo(true);
    }//GEN-LAST:event_btnImprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtAgencia;
    private javax.swing.JTextField txtConta;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
